// 9/frontend/src/pages/Login.jsx
import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import useAuthStore from '../store/authStore'
import styles from './Auth.module.css'

function Login() {
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const { login, isLoading, error } = useAuthStore()
  const navigate = useNavigate()

  const handleSubmit = async (e) => {
    e.preventDefault()
    const result = await login(username, password)
    if (result.success) {
      navigate('/')
    }
  }

  return (
    <div className={styles.container}>
      <div className={styles.card}>
        <h1 className={styles.title}>书签管理器</h1>
        <p className={styles.subtitle}>登录以管理您的书签</p>

        <form onSubmit={handleSubmit} className={styles.form}>
          {error && <div className={styles.error}>{error}</div>}

          <div className={styles.formGroup}>
            <label htmlFor="username">用户名</label>
            <input
              id="username"
              type="text"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              required
              placeholder="请输入用户名"
            />
          </div>

          <div className={styles.formGroup}>
            <label htmlFor="password">密码</label>
            <input
              id="password"
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
              placeholder="请输入密码"
            />
          </div>

          <button type="submit" className={styles.button} disabled={isLoading}>
            {isLoading ? '登录中...' : '登录'}
          </button>
        </form>

        <p className={styles.footer}>
          还没有账号？ <Link to="/register" className={styles.link}>立即注册</Link>
        </p>
      </div>
    </div>
  )
}

export default Login

// 18/frontend/src/views/Login.vue
<template>
  <div class="login-container">
    <div class="login-box">
      <h1 class="login-title">
        <o-icon icon="folder-open" pack="fas" size="large"></o-icon>
        <br>
        文件管理器
      </h1>
      
      <o-field label="用户名">
        <o-input v-model="username" placeholder="请输入用户名" @keyup.enter="login"></o-input>
      </o-field>
      
      <o-field label="密码">
        <o-input v-model="password" type="password" placeholder="请输入密码" password-reveal @keyup.enter="login"></o-input>
      </o-field>
      
      <o-button variant="primary" expanded @click="login" :loading="loading">
        登录
      </o-button>
      
      <p class="has-text-centered" style="margin-top: 15px;">
        还没有账号？
        <router-link to="/register">立即注册</router-link>
      </p>
      
      <div class="notification is-info" style="margin-top: 20px;">
        <strong>默认账号：</strong><br>
        管理员: admin / admin123<br>
        普通用户: user / user123<br>
        只读用户: viewer / viewer123
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '../stores/auth'

const router = useRouter()
const authStore = useAuthStore()

const username = ref('')
const password = ref('')
const loading = ref(false)

async function login() {
  if (!username.value || !password.value) {
    return
  }
  
  loading.value = true
  const result = await authStore.login(username.value, password.value)
  loading.value = false
  
  if (result.success) {
    router.push('/')
  } else {
    alert(result.error)
  }
}
</script>
