// 17/frontend/src/views/Login.vue
<template>
  <section class="hero is-fullheight is-light">
    <div class="hero-body">
      <div class="container">
        <div class="columns is-centered">
          <div class="column is-4">
            <div class="box">
              <h1 class="title has-text-centered">登录</h1>
              <p class="subtitle has-text-centered">URL短链接管理平台</p>
              
              <div v-if="error" class="notification is-danger">
                {{ error }}
              </div>

              <form @submit.prevent="handleLogin">
                <div class="field">
                  <label class="label">邮箱</label>
                  <div class="control">
                    <input 
                      v-model="form.email" 
                      type="email" 
                      class="input" 
                      placeholder="your@email.com"
                      required
                    />
                  </div>
                </div>

                <div class="field">
                  <label class="label">密码</label>
                  <div class="control">
                    <input 
                      v-model="form.password" 
                      type="password" 
                      class="input" 
                      placeholder="••••••"
                      required
                    />
                  </div>
                </div>

                <div class="field">
                  <div class="control">
                    <button 
                      type="submit" 
                      class="button is-primary is-fullwidth"
                      :disabled="loading"
                    >
                      <span v-if="loading">加载中...</span>
                      <span v-else>登录</span>
                    </button>
                  </div>
                </div>
              </form>

              <div class="has-text-centered mt-4">
                <p>
                  还没有账号？<router-link to="/register">立即注册</router-link>
                </p>
                <p class="is-size-7 has-text-grey mt-2">
                  测试账号: admin@example.com / admin123
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup>
import { ref } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { useAuthStore } from '@/stores/auth'

const authStore = useAuthStore()
const router = useRouter()
const route = useRoute()

const form = ref({
  email: 'admin@example.com',
  password: 'admin123'
})
const error = ref('')
const loading = ref(false)

async function handleLogin() {
  try {
    loading.value = true
    error.value = ''
    await authStore.login(form.value)
    const redirect = route.query.redirect || '/'
    router.push(redirect)
  } catch (e) {
    error.value = e.response?.data?.error || '登录失败，请重试'
  } finally {
    loading.value = false
  }
}
</script>

// 9/frontend/src/pages/Login.jsx
import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import useAuthStore from '../store/authStore'
import styles from './Auth.module.css'

function Login() {
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const { login, isLoading, error } = useAuthStore()
  const navigate = useNavigate()

  const handleSubmit = async (e) => {
    e.preventDefault()
    const result = await login(username, password)
    if (result.success) {
      navigate('/')
    }
  }

  return (
    <div className={styles.container}>
      <div className={styles.card}>
        <h1 className={styles.title}>书签管理器</h1>
        <p className={styles.subtitle}>登录以管理您的书签</p>

        <form onSubmit={handleSubmit} className={styles.form}>
          {error && <div className={styles.error}>{error}</div>}

          <div className={styles.formGroup}>
            <label htmlFor="username">用户名</label>
            <input
              id="username"
              type="text"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              required
              placeholder="请输入用户名"
            />
          </div>

          <div className={styles.formGroup}>
            <label htmlFor="password">密码</label>
            <input
              id="password"
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
              placeholder="请输入密码"
            />
          </div>

          <button type="submit" className={styles.button} disabled={isLoading}>
            {isLoading ? '登录中...' : '登录'}
          </button>
        </form>

        <p className={styles.footer}>
          还没有账号？ <Link to="/register" className={styles.link}>立即注册</Link>
        </p>
      </div>
    </div>
  )
}

export default Login
