// 17/frontend/src/views/Register.vue
<template>
  <section class="hero is-fullheight is-light">
    <div class="hero-body">
      <div class="container">
        <div class="columns is-centered">
          <div class="column is-4">
            <div class="box">
              <h1 class="title has-text-centered">注册</h1>
              <p class="subtitle has-text-centered">创建您的账号</p>
              
              <div v-if="error" class="notification is-danger">
                {{ error }}
              </div>

              <form @submit.prevent="handleRegister">
                <div class="field">
                  <label class="label">姓名</label>
                  <div class="control">
                    <input 
                      v-model="form.name" 
                      type="text" 
                      class="input" 
                      placeholder="您的姓名"
                      required
                    />
                  </div>
                </div>

                <div class="field">
                  <label class="label">邮箱</label>
                  <div class="control">
                    <input 
                      v-model="form.email" 
                      type="email" 
                      class="input" 
                      placeholder="your@email.com"
                      required
                    />
                  </div>
                </div>

                <div class="field">
                  <label class="label">密码</label>
                  <div class="control">
                    <input 
                      v-model="form.password" 
                      type="password" 
                      class="input" 
                      placeholder="至少6位密码"
                      required
                    />
                  </div>
                </div>

                <div class="field">
                  <div class="control">
                    <button 
                      type="submit" 
                      class="button is-primary is-fullwidth"
                      :disabled="loading"
                    >
                      <span v-if="loading">加载中...</span>
                      <span v-else>注册</span>
                    </button>
                  </div>
                </div>
              </form>

              <div class="has-text-centered mt-4">
                <p>
                  已有账号？<router-link to="/login">立即登录</router-link>
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'

const authStore = useAuthStore()
const router = useRouter()

const form = ref({
  name: '',
  email: '',
  password: ''
})
const error = ref('')
const loading = ref(false)

async function handleRegister() {
  try {
    loading.value = true
    error.value = ''
    await authStore.register(form.value)
    router.push('/')
  } catch (e) {
    error.value = e.response?.data?.error || '注册失败，请重试'
  } finally {
    loading.value = false
  }
}
</script>

// 9/frontend/src/pages/Register.jsx
import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import useAuthStore from '../store/authStore'
import styles from './Auth.module.css'

function Register() {
  const [formData, setFormData] = useState({
    username: '',
    email: '',
    password: '',
  })
  const { register, isLoading, error } = useAuthStore()
  const navigate = useNavigate()

  const handleSubmit = async (e) => {
    e.preventDefault()
    const result = await register(formData)
    if (result.success) {
      navigate('/')
    }
  }

  const handleChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value })
  }

  return (
    <div className={styles.container}>
      <div className={styles.card}>
        <h1 className={styles.title}>书签管理器</h1>
        <p className={styles.subtitle}>创建您的账号</p>

        <form onSubmit={handleSubmit} className={styles.form}>
          {error && <div className={styles.error}>{error}</div>}

          <div className={styles.formGroup}>
            <label htmlFor="username">用户名</label>
            <input
              id="username"
              name="username"
              type="text"
              value={formData.username}
              onChange={handleChange}
              required
              placeholder="请输入用户名"
            />
          </div>

          <div className={styles.formGroup}>
            <label htmlFor="email">邮箱</label>
            <input
              id="email"
              name="email"
              type="email"
              value={formData.email}
              onChange={handleChange}
              required
              placeholder="请输入邮箱"
            />
          </div>

          <div className={styles.formGroup}>
            <label htmlFor="password">密码</label>
            <input
              id="password"
              name="password"
              type="password"
              value={formData.password}
              onChange={handleChange}
              required
              minLength={6}
              placeholder="至少6位字符"
            />
          </div>

          <button type="submit" className={styles.button} disabled={isLoading}>
            {isLoading ? '注册中...' : '注册'}
          </button>
        </form>

        <p className={styles.footer}>
          已有账号？ <Link to="/login" className={styles.link}>立即登录</Link>
        </p>
      </div>
    </div>
  )
}

export default Register
