// 18/frontend/src/views/Register.vue
<template>
  <div class="login-container">
    <div class="login-box">
      <h1 class="login-title">
        <o-icon icon="user-plus" pack="fas" size="large"></o-icon>
        <br>
        用户注册
      </h1>
      
      <o-field label="用户名">
        <o-input v-model="username" placeholder="请输入用户名"></o-input>
      </o-field>
      
      <o-field label="邮箱">
        <o-input v-model="email" type="email" placeholder="请输入邮箱"></o-input>
      </o-field>
      
      <o-field label="密码">
        <o-input v-model="password" type="password" placeholder="请输入密码（至少6位）" password-reveal></o-input>
      </o-field>
      
      <o-button variant="primary" expanded @click="register" :loading="loading">
        注册
      </o-button>
      
      <p class="has-text-centered" style="margin-top: 15px;">
        已有账号？
        <router-link to="/login">立即登录</router-link>
      </p>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '../stores/auth'

const router = useRouter()
const authStore = useAuthStore()

const username = ref('')
const email = ref('')
const password = ref('')
const loading = ref(false)

async function register() {
  if (!username.value || !email.value || !password.value) {
    alert('请填写完整信息')
    return
  }
  
  if (password.value.length < 6) {
    alert('密码至少6位')
    return
  }
  
  loading.value = true
  const result = await authStore.register(username.value, email.value, password.value)
  loading.value = false
  
  if (result.success) {
    alert('注册成功，请登录')
    router.push('/login')
  } else {
    alert(result.error)
  }
}
</script>

// 9/frontend/src/pages/Register.jsx
import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import useAuthStore from '../store/authStore'
import styles from './Auth.module.css'

function Register() {
  const [formData, setFormData] = useState({
    username: '',
    email: '',
    password: '',
  })
  const { register, isLoading, error } = useAuthStore()
  const navigate = useNavigate()

  const handleSubmit = async (e) => {
    e.preventDefault()
    const result = await register(formData)
    if (result.success) {
      navigate('/')
    }
  }

  const handleChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value })
  }

  return (
    <div className={styles.container}>
      <div className={styles.card}>
        <h1 className={styles.title}>书签管理器</h1>
        <p className={styles.subtitle}>创建您的账号</p>

        <form onSubmit={handleSubmit} className={styles.form}>
          {error && <div className={styles.error}>{error}</div>}

          <div className={styles.formGroup}>
            <label htmlFor="username">用户名</label>
            <input
              id="username"
              name="username"
              type="text"
              value={formData.username}
              onChange={handleChange}
              required
              placeholder="请输入用户名"
            />
          </div>

          <div className={styles.formGroup}>
            <label htmlFor="email">邮箱</label>
            <input
              id="email"
              name="email"
              type="email"
              value={formData.email}
              onChange={handleChange}
              required
              placeholder="请输入邮箱"
            />
          </div>

          <div className={styles.formGroup}>
            <label htmlFor="password">密码</label>
            <input
              id="password"
              name="password"
              type="password"
              value={formData.password}
              onChange={handleChange}
              required
              minLength={6}
              placeholder="至少6位字符"
            />
          </div>

          <button type="submit" className={styles.button} disabled={isLoading}>
            {isLoading ? '注册中...' : '注册'}
          </button>
        </form>

        <p className={styles.footer}>
          已有账号？ <Link to="/login" className={styles.link}>立即登录</Link>
        </p>
      </div>
    </div>
  )
}

export default Register
